### ISSUE TITLE
Class 'Criteria' not found

### ISSUE THREAD

**Issue by michaelrimbach** [propelorm/sandbox#6]
Hello,

I have the same issue in my script as in the sandbox: http://sandbox.propelorm.org/c9d21fe
Class 'Criteria' not found

Why its not included by the composer autoloader? 
My composer.json (local project not sandbox):

{
    "name": "me/propel-project",
    "autoload": {
        "psr-0": { "": ""},
        "classmap": ["generated-classes/"] 
    },
    "require": {
        "propel/propel": "~2.0@dev",
        "monolog/monolog": "^1.17"
    }
}

Thanks your help,
Michael

**Comment by marcj** [comment]
Criteria is not at root, but in the propel namespace: `Propel\Runtime\ActiveQuery\Criteria::CONTAINS_ALL`, see http://sandbox.propelorm.org/0a5803a
